name: Checkout external docs & deploy to Netlify

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checkout-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/checkout@v2
      with:
        repository: asyncapi/generator
        path: generator-docs
    - name: Copy Generator docs
      run: "cp generator-docs/README.md pages/docs/generator/index.md"
    - name: Netlify build
      uses: netlify/actions/build@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}